// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpxsutnftykcfufiwdfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtweHN1dG5mdHlrY2Z1Zml3ZGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTM5MzYsImV4cCI6MjA2NTcyOTkzNn0.fbupyZorhMJ2b8cEmn6dh1K9RCR2QoznL9chpNJGI5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});